export type LibroBiblia = {
  nombre: string
  capitulos: number
}

export const LIBROS_BIBLIA: LibroBiblia[] = [
  // Antiguo Testamento
  { nombre: 'Génesis', capitulos: 50 },
  { nombre: 'Éxodo', capitulos: 40 },
  { nombre: 'Levítico', capitulos: 27 },
  { nombre: 'Números', capitulos: 36 },
  { nombre: 'Deuteronomio', capitulos: 34 },
  { nombre: 'Josué', capitulos: 24 },
  { nombre: 'Jueces', capitulos: 21 },
  { nombre: 'Rut', capitulos: 4 },
  { nombre: '1 Samuel', capitulos: 31 },
  { nombre: '2 Samuel', capitulos: 24 },
  { nombre: '1 Reyes', capitulos: 22 },
  { nombre: '2 Reyes', capitulos: 25 },
  { nombre: '1 Crónicas', capitulos: 29 },
  { nombre: '2 Crónicas', capitulos: 36 },
  { nombre: 'Esdras', capitulos: 10 },
  { nombre: 'Nehemías', capitulos: 13 },
  { nombre: 'Ester', capitulos: 10 },
  { nombre: 'Job', capitulos: 42 },
  { nombre: 'Salmos', capitulos: 150 },
  { nombre: 'Proverbios', capitulos: 31 },
  { nombre: 'Eclesiastés', capitulos: 12 },
  { nombre: 'Cantares', capitulos: 8 },
  { nombre: 'Isaías', capitulos: 66 },
  { nombre: 'Jeremías', capitulos: 52 },
  { nombre: 'Lamentaciones', capitulos: 5 },
  { nombre: 'Ezequiel', capitulos: 48 },
  { nombre: 'Daniel', capitulos: 12 },
  { nombre: 'Oseas', capitulos: 14 },
  { nombre: 'Joel', capitulos: 3 },
  { nombre: 'Amós', capitulos: 9 },
  { nombre: 'Abdías', capitulos: 1 },
  { nombre: 'Jonás', capitulos: 4 },
  { nombre: 'Miqueas', capitulos: 7 },
  { nombre: 'Nahúm', capitulos: 3 },
  { nombre: 'Habacuc', capitulos: 3 },
  { nombre: 'Sofonías', capitulos: 3 },
  { nombre: 'Hageo', capitulos: 2 },
  { nombre: 'Zacarías', capitulos: 14 },
  { nombre: 'Malaquías', capitulos: 4 },
  
  // Nuevo Testamento
  { nombre: 'Mateo', capitulos: 28 },
  { nombre: 'Marcos', capitulos: 16 },
  { nombre: 'Lucas', capitulos: 24 },
  { nombre: 'Juan', capitulos: 21 },
  { nombre: 'Hechos', capitulos: 28 },
  { nombre: 'Romanos', capitulos: 16 },
  { nombre: '1 Corintios', capitulos: 16 },
  { nombre: '2 Corintios', capitulos: 13 },
  { nombre: 'Gálatas', capitulos: 6 },
  { nombre: 'Efesios', capitulos: 6 },
  { nombre: 'Filipenses', capitulos: 4 },
  { nombre: 'Colosenses', capitulos: 4 },
  { nombre: '1 Tesalonicenses', capitulos: 5 },
  { nombre: '2 Tesalonicenses', capitulos: 3 },
  { nombre: '1 Timoteo', capitulos: 6 },
  { nombre: '2 Timoteo', capitulos: 4 },
  { nombre: 'Tito', capitulos: 3 },
  { nombre: 'Filemón', capitulos: 1 },
  { nombre: 'Hebreos', capitulos: 13 },
  { nombre: 'Santiago', capitulos: 5 },
  { nombre: '1 Pedro', capitulos: 5 },
  { nombre: '2 Pedro', capitulos: 3 },
  { nombre: '1 Juan', capitulos: 5 },
  { nombre: '2 Juan', capitulos: 1 },
  { nombre: '3 Juan', capitulos: 1 },
  { nombre: 'Judas', capitulos: 1 },
  { nombre: 'Apocalipsis', capitulos: 22 },
]
