-- 1. Crear la tabla para la configuración de la aplicación.
CREATE TABLE public.configuracion_app (
  clave text PRIMARY KEY,
  valor text NOT NULL
);

-- 2. Insertar el valor inicial para el monto de la penalización.
INSERT INTO public.configuracion_app (clave, valor)
VALUES ('monto_penalizacion', '5.00'); -- Valor por defecto de $5.00

-- 3. Crear el tipo ENUM para el estado de la penalización.
CREATE TYPE penalizacion_estado AS ENUM ('pendiente', 'pagada');

-- 4. Crear la tabla para registrar las penalizaciones.
CREATE TABLE public.penalizaciones (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  usuario_id uuid NOT NULL REFERENCES public.perfiles(id) ON DELETE CASCADE,
  fecha_incumplimiento date NOT NULL,
  monto numeric(10, 2) NOT NULL,
  estado penalizacion_estado NOT NULL DEFAULT 'pendiente',
  CONSTRAINT penalizacion_unica_por_usuario_y_dia UNIQUE (usuario_id, fecha_incumplimiento)
);

-- 5. Habilitar RLS para las nuevas tablas.
ALTER TABLE public.configuracion_app ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.penalizaciones ENABLE ROW LEVEL SECURITY;

-- 6. Crear políticas de seguridad RLS.
-- Cualquiera puede leer la configuración de la app.
CREATE POLICY "Los usuarios autenticados pueden leer la configuración"
ON public.configuracion_app FOR SELECT TO authenticated USING (true);

-- Los administradores pueden modificar la configuración.
CREATE POLICY "Los administradores pueden modificar la configuración"
ON public.configuracion_app FOR ALL TO authenticated
USING ((SELECT rol FROM public.perfiles WHERE id = auth.uid()) = 'admin')
WITH CHECK ((SELECT rol FROM public.perfiles WHERE id = auth.uid()) = 'admin');

-- Cualquiera puede leer todas las penalizaciones (filosofía de comunidad abierta).
CREATE POLICY "Los usuarios autenticados pueden leer todas las penalizaciones"
ON public.penalizaciones FOR SELECT TO authenticated USING (true);

-- Solo los administradores pueden actualizar el estado de una penalización (ej. a 'pagada').
CREATE POLICY "Los administradores pueden actualizar las penalizaciones"
ON public.penalizaciones FOR UPDATE TO authenticated
USING ((SELECT rol FROM public.perfiles WHERE id = auth.uid()) = 'admin');
