-- 1) Tabla perfiles
CREATE TABLE public.perfiles (
  id uuid NOT NULL PRIMARY KEY,
  nombre_usuario text NOT NULL UNIQUE CHECK (char_length(nombre_usuario) >= 3 AND char_length(nombre_usuario) <= 50),
  rol text NOT NULL DEFAULT 'usuario',
  creado_en timestamptz NOT NULL DEFAULT now()
);

-- 2) Función y Disparador para sincronizar usuarios (VERSIÓN CORREGIDA)
-- Esta función se ejecuta cuando un nuevo usuario se registra en auth.users
-- y crea una fila correspondiente en la tabla public.perfiles.
create function public.crear_perfil_para_nuevo_usuario()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.perfiles (id, nombre_usuario)
  values (new.id, new.raw_user_meta_data->>'nombre_usuario');
  return new;
end;
$$;

-- El disparador (trigger) que llama a la función anterior después de cada nuevo registro.
create trigger al_crear_usuario_auth
  after insert on auth.users
  for each row execute procedure public.crear_perfil_para_nuevo_usuario();


-- 3) Tabla planes_lectura
CREATE TABLE public.planes_lectura (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nombre_libro text NOT NULL,
  fecha_inicio timestamptz NOT NULL,
  fecha_fin timestamptz NOT NULL,
  minutos_oracion_requeridos integer NOT NULL CHECK (minutos_oracion_requeridos > 0),
  esta_activo boolean NOT NULL DEFAULT false
);

-- 4) Tabla capitulos_diarios
CREATE TABLE public.capitulos_diarios (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  plan_id bigint NOT NULL REFERENCES public.planes_lectura(id) ON DELETE CASCADE,
  fecha_lectura date NOT NULL,
  referencia_capitulo text NOT NULL,
  CONSTRAINT capitulos_diarios_unicos_por_dia UNIQUE (plan_id, fecha_lectura)
);

-- 5) Tabla progreso_usuario
CREATE TABLE public.progreso_usuario (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  usuario_id uuid NOT NULL REFERENCES public.perfiles(id) ON DELETE CASCADE,
  capitulo_id bigint NOT NULL REFERENCES public.capitulos_diarios(id),
  fecha_progreso date NOT NULL DEFAULT CURRENT_DATE,
  resumen_lectura text,
  segundos_oracion_acumulados integer NOT NULL DEFAULT 0,
  lectura_completada boolean NOT NULL DEFAULT false,
  oracion_completada boolean NOT NULL DEFAULT false,
  CONSTRAINT progreso_unico_por_usuario_y_fecha UNIQUE (usuario_id, fecha_progreso)
);

-- 6) Habilitar RLS en todas las tablas
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planes_lectura ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.capitulos_diarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.progreso_usuario ENABLE ROW LEVEL SECURITY;
