-- 1. Crear el tipo ENUM para los tipos de actividad.
CREATE TYPE tipo_actividad AS ENUM ('lectura_completada', 'oracion_completada');

-- 2. Crear la tabla para el feed de actividad.
CREATE TABLE public.actividad_comunidad (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  usuario_id uuid NOT NULL REFERENCES public.perfiles(id) ON DELETE CASCADE,
  tipo_actividad tipo_actividad NOT NULL,
  referencia_contenido text, -- Ej: "Levítico 5"
  creado_en timestamptz NOT NULL DEFAULT now()
);

-- 3. Habilitar RLS.
ALTER TABLE public.actividad_comunidad ENABLE ROW LEVEL SECURITY;

-- 4. Crear política de lectura: Cualquiera puede leer el feed.
CREATE POLICY "Los usuarios autenticados pueden leer el feed de actividad"
ON public.actividad_comunidad FOR SELECT
TO authenticated
USING (true);
